# see https://www.appveyor.com/docs/windows-images-software/#python
# and https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:

  global:
    TWINE_USERNAME: geographika
    TWINE_PASSWORD:
      secure: 6yuYlaTUIL8SRBakWTke8w==

  matrix:

    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install -r requirements-dev.txt"
  - pip install .

build_script:
  - pip install -U setuptools
  - pip install wheel
  - pip install build
  - python -m build --wheel
  - python -m build --sdist

test_script:
  - python -m pytest  # for unknown reason running pytest directly fails on Python 3.7 and above
  - "flake8 --ignore=E501,E121,E122,E123,E126,E127,E128 tests --exclude=*/basemaps/*,*/ms-ogc-workshop/*"
  - flake8 mappyfile --max-line-length=120
  - mappyfile schema mapfile-schema.json
  - mappyfile schema mapfile-schema-7-6.json --version=7.6
  - mappyfile validate tests/sample_maps/256_overlay_res.map
  - mappyfile format tests/sample_maps/256_overlay_res.map tests/sample_maps/256_overlay_res_formatted.map

deploy:
  - provider: GitHub
    auth_token:
      secure: 1FJ9ZyG2q5HxxYFSdC6HUA8+mjE9dKd55qPc6i2NZCRaOSDVog0tsoclT3e7N1sG
    draft: true
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true        # deploy on tag push only

artifacts:
  - path: 'dist\*.whl'
    name: wheel

deploy_script:
  - ps: if (($env:APPVEYOR_REPO_TAG -eq $TRUE) -and ($Env:PYTHON -ne "C:\\Python27-x64")) { pip install -qq twine; twine upload --skip-existing dist/* }

# Uncomment to enable debugging on the server
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
