# black only uses the pyproject.toml so add settings here
[tool.black]
exclude = 'tests/mapfiles'

[tool.mypy]
exclude = [
    'tests/mapfiles'
]

[[tool.mypy.overrides]]
module = [
    'jsonref',
    'glob2',
    'lark_cython',
    'PIL',
    'shapely.geometry'
]
ignore_missing_imports = true

# Flake8 does not currently support pyproject.toml
# without an additional dependency
# see https://pypi.org/project/Flake8-pyproject/

# [tool.flake8]
# max-line-length = 160
# extend-ignore = ['E203','W503']
# exclude = [
#     'build',
#     'dist',
#     'misc',
#     'tests/mapfiles',
#     'docs/_build']

[tool.pytest.ini_options]
testpaths = [
    'tests',
    'docs/examples',
]
# there is no ignore ini setting in pytest, but we can add command line options with addopts
addopts  = ['--ignore=tests/mapfiles']
# can remove the following as https://github.com/lark-parser/lark/pull/1285 has been merged
filterwarnings = 'ignore::DeprecationWarning:lark.*'