d = {   '__type__': u'map',
    u'extent': [0, 0, 100, 300],
    u'fontset': u'"../misc/fonts.lst"',
    u'imagetype': u'png',
    u'layers': [   {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'cc',
                                                              u'size': u'small',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 50]],
                                            u'text': u'"TinY#label"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'},
                   {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'ur',
                                                              u'size': u'small',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 100]],
                                            u'text': u'"SmalL#label#multiline"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'},
                   {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'uc',
                                                              u'size': u'medium',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 150]],
                                            u'text': u'"MediuM#label"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'},
                   {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'ul',
                                                              u'size': u'large',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 200]],
                                            u'text': u'"LargE#label"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'},
                   {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'cr',
                                                              u'size': u'giant',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 250]],
                                            u'text': u'"GianT#label"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'}],
    u'shapepath': u'"../misc/data"',
    u'size': [100, 300],
    u'symbolset': u'"symbolset"'}

d2 =  {u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}]
       }


d3 = {   '__type__': u'layer',
                       u'classes': [   {   '__type__': u'class',
                                           u'labels': [   {   '__type__': u'label',
                                                              u'color': [   0,
                                                                            0,
                                                                            0],
                                                              u'position': u'ur',
                                                              u'size': u'small',
                                                              u'styles': [   {   '__type__': u'style',
                                                                                 u'color': [   0,
                                                                                               255,
                                                                                               0],
                                                                                 u'geomtransform': u'labelpoly'}],
                                                              u'wrap': u"'#'"}],
                                           u'styles': [   {   '__type__': u'style',
                                                              u'color': [   255,
                                                                            0,
                                                                            0],
                                                              u'size': 5,
                                                              u'symbol': u'"circle"'}]}],
                       u'features': [   {   '__type__': u'feature',
                                            'points': [[50, 100]],
                                            u'text': u'"SmalL#label#multiline"'}],
                       u'name': u'"p1"',
                       u'status': u'default',
                       u'type': u'point'}

d4 = {u'status': u'ON', u'layers': [{u'status': u'default', u'name': u'grey', u'type': u'raster', '__type__': u'layer', 
                                     'projections': [[u'"proj=utm"', u'"zone=12"', u'"ellps=WGS84"', u'"towgs84=1,0,0"']], u'data': u'data/grey.tif'}, 
                                    {u'status': u'default', u'name': u'grid1', u'type': u'raster', '__type__': u'layer', 
                                     'projections': [[u'"proj=utm"', u'"zone=12"', u'"ellps=WGS84"', u'"towgs84=1,0,0"']], u'data': u'data/grid.gif'}],
      u'name': u'TEST', u'imagecolor': [255, 255, 0], '__type__': u'map', u'outputformats': [{'__type__': u'outputformat', u'driver': u'"GD/PNG"', u'name': u'png8_t', u'transparent': u'OFF', u'imagemode': u'PC256'}], 'projections': [[u'"proj=utm"', u'"zone=12"', u'"datum=WGS84"']], u'extent': [0.5, 0.5, 399.5, 299.5], u'imagetype': u'png8_t', u'size': [400, 300]}